# Generated by Django 4.0.5 on 2022-08-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profession', models.CharField(choices=[('it', 'It-Berufe'), ('elektro', 'Elektro-Berufe')], default='it', max_length=10)),
                ('year', models.CharField(choices=[('10', '10. Klasse'), ('11', '11. Klasse'), ('12', '12. Klasse'), ('13', '13. Klasse')], default='10', max_length=10)),
                ('group', models.CharField(choices=[('a', 'A-Block'), ('b', 'B-Block'), ('c', 'C-Block')], default='a', max_length=12)),
            ],
            options={
                'verbose_name': 'Klassen',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(verbose_name='Blockplan online stellen')),
            ],
            options={
                'verbose_name': 'Blockpläne',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('commentary', models.CharField(blank=True, default='', max_length=255, verbose_name='Kommentar')),
                ('amound_of_days', models.IntegerField(default=5)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='Zugehöriger Blockplan')),
                ('reference', models.ManyToManyField(to='plans.class')),
            ],
            options={
                'verbose_name': 'Blockwochen',
            },
        ),
    ]
