# Generated by Django 4.0.5 on 2022-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='electro',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('13', '13')], default='a', max_length=12, verbose_name='Elektro-Berufe'),
        ),
        migrations.AddField(
            model_name='week',
            name='it_10',
            field=models.CharField(choices=[('a', 'A-Block'), ('b', 'B-Block'), ('c', 'C-Block')], default='a', max_length=12, verbose_name='10. Klasse IT'),
        ),
        migrations.AddField(
            model_name='week',
            name='it_11',
            field=models.CharField(choices=[('a', 'A-Block'), ('b', 'B-Block'), ('c', 'C-Block')], default='a', max_length=12, verbose_name='11. Klasse IT'),
        ),
        migrations.AddField(
            model_name='week',
            name='it_12',
            field=models.CharField(choices=[('a', 'A-Block'), ('b', 'B-Block'), ('c', 'C-Block')], default='a', max_length=12, verbose_name='12. Klasse IT'),
        ),
        migrations.AlterField(
            model_name='week',
            name='amound_of_days',
            field=models.IntegerField(default=5, verbose_name='Anzahl an Tagen'),
        ),
        migrations.AlterField(
            model_name='week',
            name='reference',
            field=models.ManyToManyField(default='', null=True, to='plans.class', verbose_name='Klassen zuordnen'),
        ),
    ]
