# Generated by Django 4.0.5 on 2022-08-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_week_electro_week_it_10_week_it_11_week_it_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='school',
            field=models.BooleanField(default=True, verbose_name='Schulwoche'),
        ),
        migrations.AlterField(
            model_name='week',
            name='electro',
            field=models.CharField(choices=[('a', 'A-Block'), ('b', 'B-Block'), ('c', 'C-Block'), ('13', '13. Klasse')], default='a', max_length=12, verbose_name='Elektro-Berufe'),
        ),
    ]
