# Generated by Django 4.1 on 2022-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_week_school_alter_week_electro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan',
            field=models.ManyToManyField(default='', null=True, to='plans.week', verbose_name='Zugehöriger Blockplan'),
        ),
    ]
