# Generated by Django 4.1 on 2022-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_plan_plan_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='weeks',
            field=models.ManyToManyField(default='', to='plans.week', verbose_name='Zugehöriger Blockplan'),
        ),
        migrations.AlterField(
            model_name='week',
            name='reference',
            field=models.ManyToManyField(default='', to='plans.class', verbose_name='Klassen zuordnen'),
        ),
    ]
