# Generated by Django 4.1 on 2022-08-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_weeks_alter_week_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='electro',
        ),
        migrations.RemoveField(
            model_name='week',
            name='it_10',
        ),
        migrations.RemoveField(
            model_name='week',
            name='it_11',
        ),
        migrations.RemoveField(
            model_name='week',
            name='it_12',
        ),
    ]
