# Generated by Django 4.1 on 2022-08-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_remove_week_electro_remove_week_it_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='week',
            name='reference',
        ),
    ]
