# Generated by Django 4.1 on 2022-08-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_weeks_remove_week_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='weeks',
            field=models.ManyToManyField(default='', to='plans.week', verbose_name='Zugehöriger Blockplan'),
        ),
        migrations.AddField(
            model_name='week',
            name='reference',
            field=models.ManyToManyField(default='', to='plans.class', verbose_name='Klassen zuordnen'),
        ),
    ]
