# Generated by Django 4.1 on 2022-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_weeks_week_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('name',), 'verbose_name': 'Blockwochen'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='weeks',
            field=models.ManyToManyField(default='', to='plans.week', verbose_name='Wochen zuordnen'),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(default='KW<django.db.models.fields.IntegerField>', max_length=255, verbose_name='Name'),
        ),
    ]
