# Generated by Django 4.1 on 2022-09-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_week_options_alter_plan_weeks_alter_week_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('week_id',), 'verbose_name': 'Blockwochen'},
        ),
        migrations.RemoveField(
            model_name='week',
            name='name',
        ),
    ]
