# Generated by Django 4.1 on 2022-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_alter_week_options_remove_week_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Blockplan', 'verbose_name_plural': 'Blockpläne'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('week_id',), 'verbose_name': 'Blockwoche', 'verbose_name_plural': 'Blockwochen'},
        ),
        migrations.AlterField(
            model_name='week',
            name='reference',
            field=models.ManyToManyField(blank=True, to='plans.class', verbose_name='Klassen zuordnen'),
        ),
    ]
